import dash
from dash import dcc, html, Input, Output, State, callback
import requests
import datetime

BASE_URL = "http://localhost:8000"  # Backend endpoint

# Initialize Dash app
app = dash.Dash(__name__)

app.layout = html.Div([
    html.Div([
        html.H1("🌍 AI Travel Planner", style={"textAlign": "center", "marginBottom": "10px"}),
        html.H3("How can I help you in planning a trip? Let me know where do you want to visit.", 
                style={"textAlign": "center", "color": "#666", "marginBottom": "30px"}),
        
        html.Div([
            dcc.Input(
                id="user-input",
                type="text",
                placeholder="e.g. Plan a trip to Goa for 5 days",
                style={
                    "width": "100%",
                    "padding": "12px",
                    "fontSize": "16px",
                    "borderRadius": "5px",
                    "border": "1px solid #ccc",
                    "boxSizing": "border-box",
                    "height": "50px",
                    "lineHeight": "50px"
                }
            ),
            html.Button(
                "Send",
                id="submit-button",
                n_clicks=0,
                style={
                    "width": "20%",
                    "padding": "12px",
                    "marginLeft": "3%",
                    "fontSize": "16px",
                    "backgroundColor": "#4CAF50",
                    "color": "white",
                    "border": "none",
                    "borderRadius": "10px",
                    "cursor": "pointer",
                    "fontWeight": "bold"
                }
            ),
        ], style={"display": "flex", "marginTop": "20px", "gap": "10px"}),
        
        html.Div(id="loading-spinner", style={"marginTop": "20px", "textAlign": "center"}),
        html.Div(id="output-container", style={"marginTop": "30px"}),
        html.Div(id="error-message", style={"color": "red", "marginTop": "20px", "fontSize": "16px"}),
    ], style={
        "maxWidth": "900px", 
        "margin": "0 auto", 
        "padding": "40px 20px",
        "fontFamily": "Arial, sans-serif"
    })
])

@callback(
    [Output("output-container", "children"),
     Output("error-message", "children"),
     Output("user-input", "value"),
     Output("loading-spinner", "children")],
    Input("submit-button", "n_clicks"),
    State("user-input", "value"),
    prevent_initial_call=True
)
def update_output(n_clicks, user_input):
    if not user_input or not user_input.strip():
        return "", "Please enter a trip query", "", ""
    
    try:
        # Show loading message
        loading_msg = html.Div([
            html.Span("Thinking", style={"fontSize": "18px"}),
            html.Span(".", id="dot1", style={"animation": "blink 1.4s infinite"}),
            html.Span(".", id="dot2", style={"animation": "blink 1.4s infinite 0.2s"}),
            html.Span(".", id="dot3", style={"animation": "blink 1.4s infinite 0.4s"}),
        ])
        
        payload = {"question": user_input}
        response = requests.post(f"{BASE_URL}/query", json=payload)
        
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Saarankan's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""
            return dcc.Markdown(markdown_content), "", "", ""
        else:
            error_msg = f"Bot failed to respond: {response.text}"
            return "", error_msg, "", ""
    
    except Exception as e:
        error_msg = f"The response failed due to {e}"
        return "", error_msg, "", ""

if __name__ == "__main__":
    app.run(debug=True)